name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Run client tests
        run: |
          npm install
          npm run test:unit

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-pc-windows-msvc

      - name: Run webview api tests
        run: |
          cd api
          cargo test -- --test-threads 1
